/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OutgoingObjectPageObjectPage journey");

        opaTest("Navigate to OutgoingObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheOutgoingList.onFilterBar().iExecuteSearch();

            Then.onTheOutgoingList.onTable().iCheckRows();
            When.onTheOutgoingList.onTable().iPressRow(0);

            Then.onTheOutgoingObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheOutgoingObjectPage.iCheckNumberOfSections(5);
            When.onTheOutgoingObjectPage.iPressSectionIconTabFilterButton("GeneralInfo");
            Then.onTheOutgoingObjectPage.iCheckSection({ section: "GeneralInfo" });
            When.onTheOutgoingObjectPage.iPressSectionIconTabFilterButton("Parties");
            Then.onTheOutgoingObjectPage.iCheckSection({ section: "Parties" });
            When.onTheOutgoingObjectPage.iPressSectionIconTabFilterButton("MessageInfo");
            Then.onTheOutgoingObjectPage.iCheckSection({ section: "MessageInfo" });
            When.onTheOutgoingObjectPage.iPressSectionIconTabFilterButton("AttachmentInfo");
            Then.onTheOutgoingObjectPage.iCheckSection({ section: "AttachmentInfo" });
            When.onTheOutgoingObjectPage.iPressSectionIconTabFilterButton("AdminData");
            Then.onTheOutgoingObjectPage.iCheckSection({ section: "AdminData" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});