/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OutgoingListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheOutgoingList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheOutgoingList.onFilterBar().iCheckFilterField("Id");
            Then.onTheOutgoingList.onFilterBar().iCheckFilterField("Company Code");
            Then.onTheOutgoingList.onFilterBar().iCheckFilterField("Status");
            Then.onTheOutgoingList.onFilterBar().iCheckFilterField("Uuid");
            Then.onTheOutgoingList.onFilterBar().iCheckFilterField("Exstatus");
            Then.onTheOutgoingList.onFilterBar().iCheckFilterField("Document Date");
            Then.onTheOutgoingList.onFilterBar().iCheckFilterField("Solution");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // Then.onTheOutgoingList.onTable().iPressAction("Generate Number");
            Then.onTheOutgoingList.onTable().iCheckAction("Generate Number", { enabled: false });
            // Then.onTheOutgoingList.onTable().iPressAction("Check Status");
            Then.onTheOutgoingList.onTable().iCheckAction("Check Status", { enabled: false });
            // Then.onTheOutgoingList.onTable().iPressAction("Check Schematron");
            Then.onTheOutgoingList.onTable().iCheckAction("Check Schematron", { enabled: false });
            // Then.onTheOutgoingList.onTable().iPressAction("KEP Cancel");
            Then.onTheOutgoingList.onTable().iCheckAction("KEP Cancel", { enabled: false });
            // Then.onTheOutgoingList.onTable().iPressAction("E-Archive Cancel");
            Then.onTheOutgoingList.onTable().iCheckAction("E-Archive Cancel", { enabled: false });
            // Then.onTheOutgoingList.onTable().iPressAction("Regenerate XML");
            Then.onTheOutgoingList.onTable().iCheckAction("Regenerate XML", { enabled: false });
            Then.onTheOutgoingList.onTable().iCheckColumns(16, {"Id":{"header":"ID"},"Uuid":{"header":"UUID"},"Ubltyp":{"header":"UBL Type"},"Bukrs":{"header":"Company Code"},"Kunnr":{"header":"Customer"},"Sndtax":{"header":"Sender Tax No"},"Profid":{"header":"Profile ID"},"Typeid":{"header":"Document Type"},"Rcvtax":{"header":"Receiver Tax No"},"Issued":{"header":"Date"},"Status":{"header":"Status"},"Exstatus":{"header":"Ext. Status"},"Vbeln":{"header":"SD Document"},"DbKey":{"header":"DB Key"},"Exmsg":{"header":"Integrator Message"},"Exmsglong":{"header":"Integrator Long Message"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheOutgoingList.onFilterBar().iExecuteSearch();
            
            Then.onTheOutgoingList.onTable().iCheckRows();

            When.onTheOutgoingList.onTable().iPressRow(0);
            Then.onTheOutgoingObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});